//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicesCards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevicesCards()
        {
            this.DeviceRepairCards = new HashSet<DeviceRepairCards>();
        }
    
        public int Id { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string serial_no { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> firm_id { get; set; }
        public int status_id { get; set; }
        public int type_id { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceRepairCards> DeviceRepairCards { get; set; }
        public virtual Firms Firms { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual DeviceTypes DeviceTypes { get; set; }
    }
}
