//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serwis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firms()
        {
            this.DevicesCards = new HashSet<DevicesCards>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string house_no { get; set; }
        public string locum_no { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string nip { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevicesCards> DevicesCards { get; set; }
    }
}
